export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS";
export const MOSTRAR_PRODUCTO = "MOSTRAR_PRODUCTO";
export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCT0";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCT0";
